"""add selected patient to chat sessions

Revision ID: b0864f103f3f
Revises: a35967acb0f6
Create Date: 2026-07-04 01:19:49.544987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0864f103f3f'
down_revision: Union[str, Sequence[str], None] = 'a35967acb0f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('selected_patient_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'chat_sessions', 'patients', ['selected_patient_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    op.drop_column('chat_sessions', 'selected_patient_id')
    # ### end Alembic commands ###
